### ISSUE TITLE
Error occurs in "jpn_holidays.R" when data period is short

### ISSUE THREAD

**Issue by KengoTeshima** [hoxo-m/prophetExt#3]
When I executed the following, an error occurred.

```
> date_range
[1] "2017-06-01" "2018-09-27"
> holidays <- prophetExt::jpn_holidays(date_range[1], date_range[2])
Error in data.frame(holiday = "日月火3連休", ds = three$ds, lower_window = -1,  : 
  arguments imply differing number of rows: 1, 0
```

When the forecast period is short and there are few holidays, for example, the data of 4 consecutive holidays will be empty and the above error will appear.

**Comment by hoxo-m** [comment]
Resolved by PR #4. Thanks!
